/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AppRankingRouteImport } from './routes/app.ranking'
import { Route as AppMetasRouteImport } from './routes/app.metas'
import { Route as AppDashboardRouteImport } from './routes/app.dashboard'
import { Route as AppClientesRouteImport } from './routes/app.clientes'
import { Route as AppAtendentesRouteImport } from './routes/app.atendentes'
import { Route as AppAnaliseIaRouteImport } from './routes/app.analise-ia'
import { Route as AppAtendentesIdRouteImport } from './routes/app.atendentes.$id'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppRankingRoute = AppRankingRouteImport.update({
  id: '/ranking',
  path: '/ranking',
  getParentRoute: () => AppRoute,
} as any)
const AppMetasRoute = AppMetasRouteImport.update({
  id: '/metas',
  path: '/metas',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppClientesRoute = AppClientesRouteImport.update({
  id: '/clientes',
  path: '/clientes',
  getParentRoute: () => AppRoute,
} as any)
const AppAtendentesRoute = AppAtendentesRouteImport.update({
  id: '/atendentes',
  path: '/atendentes',
  getParentRoute: () => AppRoute,
} as any)
const AppAnaliseIaRoute = AppAnaliseIaRouteImport.update({
  id: '/analise-ia',
  path: '/analise-ia',
  getParentRoute: () => AppRoute,
} as any)
const AppAtendentesIdRoute = AppAtendentesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppAtendentesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/app/analise-ia': typeof AppAnaliseIaRoute
  '/app/atendentes': typeof AppAtendentesRouteWithChildren
  '/app/clientes': typeof AppClientesRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/metas': typeof AppMetasRoute
  '/app/ranking': typeof AppRankingRoute
  '/app/': typeof AppIndexRoute
  '/app/atendentes/$id': typeof AppAtendentesIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/app/analise-ia': typeof AppAnaliseIaRoute
  '/app/atendentes': typeof AppAtendentesRouteWithChildren
  '/app/clientes': typeof AppClientesRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/metas': typeof AppMetasRoute
  '/app/ranking': typeof AppRankingRoute
  '/app': typeof AppIndexRoute
  '/app/atendentes/$id': typeof AppAtendentesIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/app/analise-ia': typeof AppAnaliseIaRoute
  '/app/atendentes': typeof AppAtendentesRouteWithChildren
  '/app/clientes': typeof AppClientesRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/metas': typeof AppMetasRoute
  '/app/ranking': typeof AppRankingRoute
  '/app/': typeof AppIndexRoute
  '/app/atendentes/$id': typeof AppAtendentesIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/login'
    | '/app/analise-ia'
    | '/app/atendentes'
    | '/app/clientes'
    | '/app/dashboard'
    | '/app/metas'
    | '/app/ranking'
    | '/app/'
    | '/app/atendentes/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/app/analise-ia'
    | '/app/atendentes'
    | '/app/clientes'
    | '/app/dashboard'
    | '/app/metas'
    | '/app/ranking'
    | '/app'
    | '/app/atendentes/$id'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/login'
    | '/app/analise-ia'
    | '/app/atendentes'
    | '/app/clientes'
    | '/app/dashboard'
    | '/app/metas'
    | '/app/ranking'
    | '/app/'
    | '/app/atendentes/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/ranking': {
      id: '/app/ranking'
      path: '/ranking'
      fullPath: '/app/ranking'
      preLoaderRoute: typeof AppRankingRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/metas': {
      id: '/app/metas'
      path: '/metas'
      fullPath: '/app/metas'
      preLoaderRoute: typeof AppMetasRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/dashboard': {
      id: '/app/dashboard'
      path: '/dashboard'
      fullPath: '/app/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/clientes': {
      id: '/app/clientes'
      path: '/clientes'
      fullPath: '/app/clientes'
      preLoaderRoute: typeof AppClientesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/atendentes': {
      id: '/app/atendentes'
      path: '/atendentes'
      fullPath: '/app/atendentes'
      preLoaderRoute: typeof AppAtendentesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/analise-ia': {
      id: '/app/analise-ia'
      path: '/analise-ia'
      fullPath: '/app/analise-ia'
      preLoaderRoute: typeof AppAnaliseIaRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/atendentes/$id': {
      id: '/app/atendentes/$id'
      path: '/$id'
      fullPath: '/app/atendentes/$id'
      preLoaderRoute: typeof AppAtendentesIdRouteImport
      parentRoute: typeof AppAtendentesRoute
    }
  }
}

interface AppAtendentesRouteChildren {
  AppAtendentesIdRoute: typeof AppAtendentesIdRoute
}

const AppAtendentesRouteChildren: AppAtendentesRouteChildren = {
  AppAtendentesIdRoute: AppAtendentesIdRoute,
}

const AppAtendentesRouteWithChildren = AppAtendentesRoute._addFileChildren(
  AppAtendentesRouteChildren,
)

interface AppRouteChildren {
  AppAnaliseIaRoute: typeof AppAnaliseIaRoute
  AppAtendentesRoute: typeof AppAtendentesRouteWithChildren
  AppClientesRoute: typeof AppClientesRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppMetasRoute: typeof AppMetasRoute
  AppRankingRoute: typeof AppRankingRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAnaliseIaRoute: AppAnaliseIaRoute,
  AppAtendentesRoute: AppAtendentesRouteWithChildren,
  AppClientesRoute: AppClientesRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppMetasRoute: AppMetasRoute,
  AppRankingRoute: AppRankingRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
